FROM node:22.20-bookworm-slim
ARG NEXT_PUBLIC_VERSION
ENV NEXT_PUBLIC_VERSION=$NEXT_PUBLIC_VERSION
RUN apt-get update && apt-get install -y --no-install-recommends \
    g++ \
    make \
    python3-pip \
    bash \
    nginx \
&& rm -rf /var/lib/apt/lists/*

RUN addgroup --system www \
 && adduser --system --ingroup www --home /www --shell /usr/sbin/nologin www \
 && mkdir -p /www \
 && chown -R www:www /www /var/lib/nginx


RUN npm --no-update-notifier --no-fund --global install pnpm@10.6.1 pm2

WORKDIR /app

# --- OPTIMIZATION START ---
# Only copy the files that define your dependencies first
# This catches everything in the workspace
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/frontend/package.json ./apps/frontend/
COPY apps/backend/package.json ./apps/backend/
COPY apps/orchestrator/package.json ./apps/orchestrator/
COPY apps/commands/package.json ./apps/commands/
COPY apps/cli/package.json ./apps/cli/
COPY apps/extension/package.json ./apps/extension/
COPY apps/sdk/package.json ./apps/sdk/

# Run install. This will stay cached unless you add a new library!
RUN pnpm install --no-frozen-lockfile --ignore-scripts
# --- OPTIMIZATION END ---

# Now copy the rest of your code
COPY . /app
COPY var/docker/nginx.conf /etc/nginx/nginx.conf

# FINAL INSTALL: This resolve all workspace links now that the folders exist.
# Since the previous step already cached everything, this will take seconds.
RUN pnpm install

RUN pnpm run prisma-generate
RUN NODE_OPTIONS="--max-old-space-size=4096" pnpm run build

CMD ["sh", "-c", "nginx && pnpm run pm2"]
